version: '3.8'

services:
  client:
    image: node:lts-stretch-slim
    ports:
      # Needed for app
      - 3000:3000
      # Needed for firebase
      - 9005:9005
    volumes:
      - ./:/app
    working_dir: /app
    # Remove me when cra did release https://github.com/facebook/create-react-app/issues/8688#issuecomment-642331184
    stdin_open: true
    command: bash -c "npm install && npm start"
